README.md
src/create-template/pvs.ts

set scale, update badges

---

.github/pull_request_template.md
.prettierignore
README.md
package.json
src/commands/create-parts.ts
src/commands/create-scene.ts
yarn.lock

Requires https://github.com/Vertexvis/vertex-api-client-ts/pull/5
n/a
n/a

[DATA-1343]: Increase parallelism, upgrade api-client, strip './' from template path

---

README.md
package.json
src/base.ts
src/commands/create-parts.ts
src/commands/create-scene.ts
src/commands/create-stream-key.ts
src/commands/create-template.ts
src/commands/render-image.ts
src/create-template/pvs.ts
tsconfig.json
yarn.lock

Requires https://github.com/Vertexvis/vertex-api-client-ts/pull/6.
Also fixes a partial file upload issue, skips already created parts, and allows you to pass a root component into `create-template` so you can generate one for a sub-assembly.
n/a
n/a

[DATA-1345]: Add base command for common flags, add create-stream-key and render-image, use latest api-client

---

README.md
package.json
src/base.ts
src/commands/create-parts.ts
src/commands/create-scene.ts
src/commands/create-stream-key.ts
src/commands/render-image.ts
tsconfig.json
yarn.lock

[DATA-1345]: Add 'dom' to tsconfig lib to fix publish. Use latest api-client to allow string environments

---

.gitignore
.prettierignore
README.md
package.json
src/commands/create-scene.ts
tsconfig.json
yarn.lock

Requires https://github.com/Vertexvis/vertex-api-client-ts/pull/8.
n/a
n/a

[DATA-1259]: Pull in new api-client, use basename on scene creation

---

README.md
package.json
src/base.ts
src/commands/create-parts.ts
src/commands/create-scene.ts
src/commands/create-stream-key.ts
src/commands/render-image.ts
yarn.lock

[API-1358]: Allow setting basePath instead of enviornment

---

README.md
package.json
yarn.lock

[DATA-1334]: Update api client

---

README.md
package.json
src/base.ts
src/commands/create-parts.ts
src/commands/create-scene.ts
src/commands/create-stream-key.ts
src/commands/create-template.ts
src/commands/render-image.ts
src/create-template/pvs.ts
yarn.lock

- Parse properties for suppliedRevisionId
- Add spinner for long running tasks
- Handle new errors from api-client
- Add flag to configure parallelism
n/a
n/a

[API-1372]: Improvements based on customer feedback

---

README.md
package.json
yarn.lock

[API-1372]: Update api-client

---

.github/workflows/automerge.yml
.github/workflows/build.yml
.github/workflows/publish.yml
README.md
package.json
src/commands/create-parts.ts
src/commands/create-scene.ts
src/create-template/index.d.ts
src/create-template/pvs.ts
tsconfig.json
yarn.lock

Add an `--experimental` flag to `create-scene` that creates with `scene-items` instead of from a template.
n/a
n/a

[API-1372]: Create scene with scene items

---

README.md
package.json
tsconfig.json
yarn.lock

Update api-client, set node version to >=12.10 so `Promise.allSettled` works on file upload.
n/a
n/a

[API-1372]: Update api-client, restrict node engine

---

README.md
package.json
src/commands/create-parts.ts
src/create-template/pvs.ts

[API-1408]: Do not set source if no geometry

---

.prettierignore
README.md
package.json
src/commands/create-parts.ts
src/commands/create-scene.ts
src/create-items/index.d.ts
src/create-items/pvs.ts
yarn.lock

You can now upload a single JT/STEP/etc file, making this much more useful. Details in README.

[API-1472]: Update deps, move part information to 'source', allow uploading single part file

---

README.md
package.json
src/commands/create-scene.ts
src/commands/create-stream-key.ts
src/commands/delete.ts
src/commands/render-image.ts
yarn.lock

Requires https://github.com/Vertexvis/vertex-api-client-ts/pull/40

[API-1492]: Fix delete command

---

package.json
src/lib/deleter.ts

[API-1863] Bump page sizes to 200

---

README.md
package.json
src/commands/scene-view-states/delete.ts
src/commands/scene-view-states/get.ts
src/commands/scene-view-states/list.ts
src/lib/deleter.ts
src/lib/getter.ts
yarn.lock

[API-1949]: Add scene-view-state CRUD operations

---

README.md
package.json
src/commands/files/delete.ts
src/commands/files/get.ts
src/commands/part-revisions/render.ts
src/commands/parts/delete.ts
src/commands/parts/get.ts
src/commands/scene-view-states/delete.ts
src/commands/scene-view-states/get.ts
src/commands/scene-views/get.ts
src/commands/scene-views/list.ts
src/commands/scene-views/render.ts
src/commands/scenes/delete.ts
src/commands/scenes/get.ts
src/commands/scenes/render.ts
src/lib/getter.ts
test/commands/scenes/get.test.ts
yarn.lock

[API-1974]: Add scene-views:get and scene-views:list

---

README.md
package.json
src/lib/renderer.ts

[API-2060]: Fix renderer

---

LICENSE
README.md
package.json
src/commands/create-parts.ts
yarn.lock

[API-2206]: Update deps, stop using deprecated method

---

README.md
package.json
src/lib/client.ts
src/lib/renderer.ts

[API-2257]: Remove timeout as it affects file uploads

---

README.md
package.json
yarn.lock

[API-2261]: Update client

---

README.md
package.json
src/commands/scene-items/get.ts
src/commands/scene-items/list.ts
src/commands/scene-views/create.ts
src/lib/getter.ts
test/commands/files/get.test.ts
test/commands/parts/get.test.ts
test/commands/scene-items/get.test.ts
test/commands/scene-view-states/get.test.ts
test/commands/scene-views/get.test.ts
yarn.lock

* Add scene-items:get, scene-items:list, and scene-views:create CLI commands

[API-2287] Add scene-items:list, scene-items:get, and scene-views:create

---

README.md
package.json
src/commands/exports/create.ts
src/commands/exports/get.ts
src/lib/getter.ts
test/commands/exports/create.test.ts
test/commands/exports/get.test.ts
yarn.lock

New cli commands to create and then get exports.  The get will also download the file using the pre-signed url provided
Local test example:

[PLAT-1074] create and get exports

---

README.md
package.json
src/commands/exports/download.ts
src/lib/getter.ts
test/commands/exports/download.test.ts
yarn.lock

Separate the `exports:get` into a command that gets the export resource `exports:get` and a command that downloads resulting file `exports:download`

Plat 1074 split exports:get command into get and download

---

README.md
package.json
src/commands/scenes/render.ts
src/lib/renderer.ts

Switch the template to use the `@ .15.x` version instead of a pinned version.
generate an app of a scene using the scene:render command
[Ticket](https://vertexvis.atlassian.net/browse/PLAT-1153)

[PLAT-1153] - Use 0.15.x @vertex/viewer

---

README.md
package.json

Release v0.16.4

---

README.md
package.json
src/commands/create-scene.ts

Added detection to prevent CLI from sending scene item creation requests for duplicate supplied IDs when using the experimental scene creation strategy.

[PLAT-2038] Added detection for duplicate scene items

---

package.json
yarn.lock

There was a bug in the node-client-helpers that is now resolved with version 0.22.3. This change is to bump the dependency.

[PLAT-4011] Using fixed node-client-helpers

---

package.json
src/lib/renderer.ts

- Replaces the cdn to one that is more performant
- Bumps to the latest vertex viewer version

[PLAT-4506] Using JSDelivr instead of Unpkg for performance improvements

---

README.md
package.json
yarn.lock

Fixing publish for version 0.18.5
